# Generated by Django 4.2.7 on 2023-11-25 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("programming", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Programming",
        ),
        migrations.RenameField(
            model_name="programming",
            old_name="name",
            new_name="language",
        ),
        migrations.RenameField(
            model_name="programming",
            old_name="price",
            new_name="since",
        ),
    ]
