# Generated by Django 4.2.7 on 2023-11-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programming", "0002_rename_product_programming_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
            ],
        ),
    ]
