name: Deploy

on:
  push:
    branches:
    - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]
  
    steps:
    - uses: actions/checkout@v3
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 64.227.178.58
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd root/telegrambot/
          source ./venv/bin/activate
          git pull
          python manage.py migrate
          python manage.py collectstatic --noinput
          supervisorctl restart all
    

  
